/**
 * Name: Zulkifli Salami
 * Code snippet generated with the assistance of ChatGPT, an AI language model developed by OpenAI.

  Assistance provided by:
  - ChatGPT (OpenAI GPT-4 model), which provided guidelines and examples for the code structure and logic.
  
  Note: The code generated by AI is a starting point and has been adapted and verified by Zulkifli Salami to fit the specific needs of this project.
  
  Date of Generation: 03/21/2024
  Code Generator: ChatGPT by OpenAI
  Version: GPT-4
  URL: https://openai.com/chatgpt
 */

const homeView = (req, res) => {
    res.render('home');
};

const page1View = (req, res) => {
    res.render('page1');
};

const page2View = (req, res) => {
    res.render('page2');
};

const handleFormSubmit = (req, res) => {
    res.redirect('/success'); // Redirect or handle the response as needed
};

const successView = (req, res) => {
    res.render('success');
};


module.exports = { homeView, page1View, page2View, handleFormSubmit, successView };
