/**
 * Name: Zulkifli Salami
 * Code snippet generated with the assistance of ChatGPT, an AI language model developed by OpenAI.

  Assistance provided by:
  - ChatGPT (OpenAI GPT-4 model), which provided guidelines and examples for the code structure and logic.
  
  Note: The code generated by AI is a starting point and has been adapted and verified by Zulkifli Salami to fit the specific needs of this project.
  
  Date of Generation: 03/21/2024
  Code Generator: ChatGPT by OpenAI
  Version: GPT-4
  URL: https://openai.com/chatgpt
 */

const express = require('express');
const dotenv = require('dotenv').config(); // Loads environment variables from .env file
const userRoutes = require('./routes/user');

// Initialize Express
const app = express();

// Set the view engine to pug
app.set('view engine', 'pug');

app.use(express.urlencoded({ extended: true })); // For parsing application/x-www-form-urlencoded
// Use the router for the '/' view
app.use('/', userRoutes);

// Defines a port to listen to
const port = process.env.PORT; // Uses the PORT environment variable

// Start the server
app.listen(port, () => {
    console.log(`Server running on port ${port}`);
});
